import { defineConfig } from 'oxfmt';

export default defineConfig({
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'strict',
  ignorePatterns: ['.agents/skills/**'],
  insertFinalNewline: true,
  jsdoc: {
    addDefaultToDescription: true,
    bracketSpacing: false,
    capitalizeDescriptions: true,
    commentLineStrategy: 'singleLine',
    descriptionWithDot: true,
    lineWrappingStyle: 'greedy',
    preferCodeFences: true,
    separateReturnsFromParam: true,
    separateTagGroups: true,
  },
  jsxSingleQuote: true,
  objectWrap: 'collapse',
  printWidth: 80,
  proseWrap: 'always',
  quoteProps: 'as-needed',
  semi: true,
  singleAttributePerLine: true,
  singleQuote: true,
  sortImports: {
    groups: [
      'type-import',
      ['value-builtin', 'value-external'],
      'type-internal',
      'value-internal',
      ['type-parent', 'type-sibling', 'type-index'],
      ['value-parent', 'value-sibling', 'value-index'],
      'style',
      'unknown',
    ],
    ignoreCase: false,
    newlinesBetween: true,
    order: 'asc',
    partitionByComment: false,
    partitionByNewline: false,
    sortSideEffects: false,
  },
  sortPackageJson: { sortScripts: true },
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
});
